
Generate SQL
CREATE TABLE STORE
(
  StoreID INT NOT NULL,
  ORG INT NOT NULL,
  Address INT NOT NULL,
  PRIMARY KEY (StoreID),
  UNIQUE (Address)
);

CREATE TABLE MANAGER
(
  AdminID INT NOT NULL,
  AdminPrvLvl INT NOT NULL,
  FirstName INT NOT NULL,
  LastName INT NOT NULL,
  PRIMARY KEY (AdminID)
);

CREATE TABLE LAYOUT
(
  LayoutID INT NOT NULL,
  StoreID INT NOT NULL,
  PRIMARY KEY (LayoutID),
  FOREIGN KEY (StoreID) REFERENCES STORE(StoreID)
);

CREATE TABLE CUSTOMER
(
  CustID INT NOT NULL,
  FirstName INT NOT NULL,
  LastName INT NOT NULL,
  PRIMARY KEY (CustID)
);

CREATE TABLE Manages
(
  StoreID INT NOT NULL,
  AdminID INT NOT NULL,
  PRIMARY KEY (StoreID, AdminID),
  FOREIGN KEY (StoreID) REFERENCES STORE(StoreID),
  FOREIGN KEY (AdminID) REFERENCES MANAGER(AdminID)
);

CREATE TABLE STORE_phoneNumber
(
  phoneNumber INT NOT NULL,
  StoreID INT NOT NULL,
  PRIMARY KEY (phoneNumber, StoreID),
  FOREIGN KEY (StoreID) REFERENCES STORE(StoreID)
);

CREATE TABLE MANAGER_Email
(
  Email INT NOT NULL,
  AdminID INT NOT NULL,
  PRIMARY KEY (Email, AdminID),
  FOREIGN KEY (AdminID) REFERENCES MANAGER(AdminID)
);

CREATE TABLE MANAGER_MngPhoneNum
(
  MngPhoneNum INT NOT NULL,
  AdminID INT NOT NULL,
  PRIMARY KEY (MngPhoneNum, AdminID),
  FOREIGN KEY (AdminID) REFERENCES MANAGER(AdminID)
);

CREATE TABLE CUSTOMER_Email
(
  Email INT NOT NULL,
  CustID INT NOT NULL,
  PRIMARY KEY (Email, CustID),
  FOREIGN KEY (CustID) REFERENCES CUSTOMER(CustID)
);

CREATE TABLE SPACE
(
  SpaceID INT NOT NULL,
  SpaceDesignator_ INT NOT NULL,
  NumSeats INT NOT NULL,
  SpatialLocation INT NOT NULL,
  SpaceType INT NOT NULL,
  CustID INT,
  LayoutID INT NOT NULL,
  PRIMARY KEY (SpaceID, CustID),
  FOREIGN KEY (CustID) REFERENCES CUSTOMER(CustID),
  FOREIGN KEY (LayoutID) REFERENCES LAYOUT(LayoutID)
);